![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np
my_array = np.arange(10)
my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [20]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [37]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [42]:
matriz = np.arange(1, 21).reshape(4, 5)

In [43]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [45]:
invertir = matriz[::-1, ::-1]
print(invertir)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [46]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [48]:
obten = matriz[:2, :2]
print(obten)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [49]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [55]:
obten2 = matriz[[0, 2],:][...,[0,2,4]]
print(obten2)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [57]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [60]:
obten3 = matriz[:3, ::-1]
print(obten3)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [93]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [94]:
loro = x[np.where(x == "Loro")]
print(loro)

['Loro' 'Loro']


In [102]:
loro = x[x == "Loro"]
print(loro)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [62]:
secuencia = np.arange(1, 21)
matriz1 = secuencia[:10].reshape(5, 2)
matriz2 = secuencia[10:].reshape(5, 2)

print(matriz1)
print(matriz2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [ ]:
my_array

In [63]:
invertir = matriz[::-1, ::-1]
print(invertir)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [64]:
array_zero = np.zeros(10, dtype=np.int32)
cuanto = array_zero.nbytes
print(array_zero)
print(cuanto)

[0 0 0 0 0 0 0 0 0 0]
40


In [65]:
array_zero[3] = 1
print(array_zero)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [66]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [78]:
vector = np.array([1, 2, 0, 0, 4, 0])

In [80]:
indices = np.where(vector != 0)[0]
print(indices)

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [8]:
matriz14 = np.random.randint(100, size=(10, 10))
print(matriz14)
print("Mínimo", np.min(matriz14), matriz14.min())
print("Máximo", np.max(matriz14), matriz14.max())

[[29 83 79 13 22  9 96 83 14 72]
 [23 30 36 61 29 79 42 46 92 70]
 [44 63 47 90  1 66 28 38 77 87]
 [22 75 14 75 34 70 91 72 25 40]
 [ 0 97 38  0 68 69 61 25 30 89]
 [59 55 88 19 25 76 93 29 45  0]
 [97 88 87 74 66 36 29 47 32 34]
 [41  1 11 37 31 98 87 72 13 88]
 [11  4 36 61 31 26 55 94 86 15]
 [76 16 40 89 29 69 67  1 17 33]]
Mínimo 0 0
Máximo 98 98


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [81]:
vector15 = np.random.rand(30)
media = np.mean(vector15)
print(media)

0.5889645084546982


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [83]:
dim = 6

In [91]:
array2d = np.zeros((dim,dim), dtype=int)
array2d[0, :] = 1
array2d[:, 0] = 1
array2d[-1, :] = 1
array2d[:, -1] = 1
print(array2d)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [96]:
mtriz = np.zeros((8, 8), dtype=int)
print(mtriz)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
mtriz[1::2, ::2]= 1
mtriz[::2, 1::2]= 1
print(mtriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
a = np.array([[0, 1],[1, 0]])

mtriz = np.tile(a, (4, 4))
print(mtriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [99]:
np.random.seed(1000)
x19 = np.random.randint(1, 20, (5,5))
print(x19)

[[ 8  1  2  1 14]
 [ 9 10  5 14 16]
 [11 10  5 19 10]
 [19 14 19 11 15]
 [ 6 13 12 12  1]]


In [101]:
x19 = (x19-np.mean(x19)/np.std(x19))
print(x19)

[[ 6.11942269 -0.88057731  0.11942269 -0.88057731 12.11942269]
 [ 7.11942269  8.11942269  3.11942269 12.11942269 14.11942269]
 [ 9.11942269  8.11942269  3.11942269 17.11942269  8.11942269]
 [17.11942269 12.11942269 17.11942269  9.11942269 13.11942269]
 [ 4.11942269 11.11942269 10.11942269 10.11942269 -0.88057731]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [3]:
x = np.arange(11)
print(x)

y = x.copy()
y[(y >= 3) & (y <= 8)] = -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [4]:
z = x.copy()
z[(z >= 3) & (z <= 8)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.